image: node:14.15.5-alpine3.10

stages:
  - test
  - report

cache:
  paths:
    - node_modules/
    - allure-results/

test:
  stage: test
  services:
    - selenium/standalone-chrome
  script:
    - npm ci
    - npm run test:gitlab

report:
  stage: report
  script:
    - apk add openjdk11
    - JAVA_HOME=/usr/lib/jvm/java-11-openjdk
    - export JAVA_HOME
    - npm run report:generate
  artifacts:
    expire_in: 30 days
    paths:
      - allure-report
  when: always
